# Generated by Django 4.1.1 on 2022-09-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('DOB', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(choices=[('Uttar Pradesh', 'uttar pradesh'), ('Delhi', 'delhi'), ('Himachal Pradesh', 'himachal pradesh')], max_length=225)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('resume', models.FileField(blank=True, upload_to='resumes')),
            ],
        ),
    ]
