# Generated by Django 4.1.1 on 2022-09-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
